{% set ENV_NAME         = os.environ.get('ENV_NAME', 'dev') %}

{% set VER_PYTHON       = os.environ.get('VER_PYTHON') %}
{% set VER_CUDA         = os.environ.get('VER_CUDA') %}

{% set CUDA_CHANNEL     = 'nvidia/label/cuda-' + VER_CUDA %}
{% set CU               = 'cu' + ''.join(VER_CUDA.split('.')[:-1]) if VER_CUDA != '' else 'cpu' %}


name: {{ ENV_NAME }}

{% if CU != 'cpu' %}
channels:
  - {{ CUDA_CHANNEL }}
{% endif %}

dependencies:
  - auditwheel
  - patchelf
  - python={{ VER_PYTHON }}
  - python-build
  - pip
{% if CU != 'cpu' %}
  - cuda-gdb
  - cuda-nvcc
  - cuda-nvtx
  - cuda-libraries-dev
  - cudnn
{% endif %}
